# SPDX-License-Identifier: BSD-3-Clause
"""Validate tttrlib's PicoQuant T2 decoding against the independent ``ptufile``
reference decoder (Christoph Gohlke).

The tttrlib golden ``.npz`` references are generated by tttrlib itself, so they
cannot catch a systematic decode error. ``ptufile`` is an independent
implementation; this test compares the decoded photon stream (macro time +
routing channel) of a real HydraHarp T2 file against it.

In particular it guards the sync-channel semantics: in HydraHarp/MultiHarp T2 a
``special`` record with ``channel == 0`` is the sync input and must decode as a
photon on channel 0 (as ptufile does), not as a marker.
"""
import os
import sys
import unittest

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))
from test_settings import settings, DATA_AVAILABLE  # type: ignore

import tttrlib

try:
    import ptufile
    HAVE_PTUFILE = True
except ImportError:
    HAVE_PTUFILE = False

RECORD_PHOTON = 0


@unittest.skipIf(not DATA_AVAILABLE, "Data directory not found")
@unittest.skipIf(not HAVE_PTUFILE, "ptufile not installed")
class TestT2PtufileReference(unittest.TestCase):

    def _photons_tttrlib(self, fn):
        d = tttrlib.TTTR(fn, "PTU")
        et = np.asarray(d.event_types)
        is_ph = et == RECORD_PHOTON
        return (np.asarray(d.macro_times)[is_ph].astype(np.uint64),
                np.asarray(d.routing_channels)[is_ph].astype(np.int64))

    def _photons_ptufile(self, fn):
        p = ptufile.PtuFile(fn)
        recs = p.decode_records()
        # ptufile marks overflow/special non-photon records with channel < 0.
        is_ph = (recs["channel"] >= 0) & (recs["marker"] == 0)
        return (recs["time"][is_ph].astype(np.uint64),
                recs["channel"][is_ph].astype(np.int64))

    def test_hh_t2_matches_ptufile(self):
        fn = settings["ptu_hh_t2_filename"]
        if not os.path.isfile(fn):
            self.skipTest("missing data file: %s" % fn)

        t_time, t_chan = self._photons_tttrlib(fn)
        r_time, r_chan = self._photons_ptufile(fn)

        self.assertEqual(t_time.size, r_time.size,
                         "photon count differs from ptufile")
        np.testing.assert_array_equal(t_time, r_time)
        np.testing.assert_array_equal(t_chan, r_chan)

        # The file must actually contain sync (channel 0) photons, otherwise the
        # test would pass trivially without exercising the sync-channel path.
        self.assertGreater(int((r_chan == 0).sum()), 0,
                           "reference file has no channel-0 sync photons")


if __name__ == "__main__":
    unittest.main()
