dist: xenial
language: python
sudo: required
python:
  - "3.7"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then MINICONDA_OS=Linux; else MINICONDA_OS=MacOSX; fi
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-$MINICONDA_OS-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda config --set channel_priority strict
  - conda config --add channels conda-forge
  - conda info -a
  - conda install git conda-build anaconda-client
  - git clone https://github.com/Fluorescence-Tools/conda-recipes.git
  - conda build conda-recipes/tttrlib --output-folder bld-dir
  - conda config --add channels "file://`pwd`/bld-dir"

install:
  - conda install tttrlib

script:
  - conda install nose coverage
  - ln -sf $(which nosetests) $(pwd)/test/
  - cd $(pwd)/test/
  - echo $PWD
  - nosetests --with-coverage test_*.py

# deploy
after_success:
  - OS=$TRAVIS_OS_NAME-64
  - pip install codacy-coverage
  - coverage xml
  - python-codacy-coverage -r coverage.xml
  - |
    if [[ "$TRAVIS_BRANCH" == "master" ]];
    then
      ls bld-dir/linux-64/
      anaconda upload bld-dir/**/tttrlib*.tar.bz2
    fi

