dist: xenial
language: python
sudo: required
python:
  - "3.7"
before_install:
  - git submodule update --init --recursive
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then MINICONDA_OS=Linux; else MINICONDA_OS=MacOSX; fi
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-$MINICONDA_OS-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda env create -f environment.yaml
  - source activate tttrlib
  - python setup.py build --force
install:
  - python setup.py install
script:
  - source activate tttrlib
  - conda install nose coverage
  - ln -sf $(which nosetests) $(pwd)/test/
  - cd $(pwd)/test/
  #- nosetests --with-coverage test_*.py
after_success:
  - source activate tttrlib
  - pip install codacy-coverage
  - coverage xml
  - python-codacy-coverage -r coverage.xml
