language: generic
sudo: required

matrix:
  include:
    - os: linux
      dist: bionic
    - os: osx
      osx_image: xcode9.4

env:
  # Build and test package on all supported python versions
  - BUILD_TARGET=3.7 MINICONDA_VERSION=latest

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then MINICONDA_OS=Linux; else MINICONDA_OS=MacOSX; fi
  # unlink homebrew's boost so that is does not interfere with conda's boost in the build process
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew unlink boost; fi
  - wget https://repo.continuum.io/miniconda/Miniconda3-$MINICONDA_VERSION-$MINICONDA_OS-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  # scipy is used in some tests
  - conda install python=$BUILD_TARGET conda-build anaconda-client jinja2 git nose coverage anaconda-client scipy doxygen
  - source activate base
  - git fetch --unshallow --tags --force
  - conda build conda-recipe --output-folder bld-dir
  - conda config --add channels "file://`pwd`/bld-dir"

install:
  - conda install tttrlib -c "file://`pwd`/bld-dir"

script:
  # create a link from nosetests in test to make sure that the correct nosetests is used
  - ln -sf $(which nosetests) $(pwd)/test/
  - cd $(pwd)/test/
  - echo $PWD
  - nosetests --with-coverage test_*.py
  - cd ..

after_success:
  - OS=$TRAVIS_OS_NAME-64
  - pip install codacy-coverage
  - coverage xml
  - python-codacy-coverage -r coverage.xml
  # build the documentation only on linux and upload build
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]
    then
      # The documentation is only build using the linux conda dist
      # Hence only upload linux nightly
      conda activate base
      anaconda -t $ANACONDA_API_TOKEN upload -u $CONDA_USER -l nightly bld-dir/$OS/*.tar.bz2 --force
      cd docs
      conda env create -f environment.yml
      conda activate docs_env
      conda install doxygen -c conda-forge
      # Use Sphinx to make the html docs the doxygen docs are build with breathe
      make clean
      make html
      touch _build/html/.nojekyll
      cd ..
      conda deactivate
    fi


# Tell Travis CI to copy the documentation to the gh-pages branch of
# your GitHub repository.
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: development
    condition: $TRAVIS_OS_NAME = linux
  local_dir: docs/_build/html/


notifications:
  email:
    recipients:
      - thomas.otavio.peulen@gmail.com
    on_success: change # default: change
    on_failure: change # default: always
