name: tttrlib

channels:
  - fluorescence-tools
  - tpeulen
  - conda-forge
  - salilab
  - defaults

dependencies:
  - python=3.7
  - setuptools
  - numpy
  - swig
  - hdf5
  - boost
  - cmake
  - sphinx
  - openmp
  - ipython
  - matplotlib
  - yaml
