name: tttrlib

channels:
  - conda-forge
  - defaults

dependencies:
  - python 3.7.*
  - setuptools
  - numpy
  - swig
  - hdf5 1.10.5.*
  - boost
  - cmake
  - sphinx
  - openmp
  - ipython
  - matplotlib
  - yaml
  - sphinx
  - sphinxcontrib-bibtex
  - recommonmark
  - nose
  - conda-build
  - nose
  - anaconda-client
