name: tttrlib

channels:
  - fluorescence-tools
  - tpeulen
  - conda-forge
  - salilab
  - defaults

dependencies:
  - python=3.7
  - setuptools
  - numpy
  - swig
  - hdf=1.8.16 # [win]
  - hdf>=1.8.16 # [linux]
  - cmake
  - sphinx
  - openmp
