name: tttrlib

channels:
  - fluorescence-tools
  - tpeulen
  - conda-forge
  - salilab
  - defaults

dependencies:
  - python=3.7
  - setuptools
  - numpy
  - swig
  - hdf5=1.8.16 [win]
  - hdf5=1.8.16 [osx]
  - hdf5 [linux]
  - cmake
  - sphinx
  - openmp
  - ipython
  - matplotlib
