name: tttrlib

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.7
  - setuptools
  - numpy
  - swig
  - hdf5
  - boost
  - cmake
  - sphinx
  - openmp
  - ipython
  - matplotlib
  - yaml
  - sphinx
  - sphinxcontrib-bibtex
  - recommonmark
  - clang_osx-64 [osx]
  - clangxx_osx-64 [osx]
  - gcc_linux-64 [linux]
  - gxx_linux-64 [linux]
  - nose

