name: tttrlib

channels:
  - defaults

dependencies:
  - python
  - cmake
  - swig 3.0.12.*
  - setuptools
  - numpy
  - hdf5 1.10.2.*
  - boost 1.67.0.*
  - libboost 1.67.0.*
  - yaml
  - nose
  - anaconda-client
  - conda-build
  - fftw
  - ninja
  - scipy
  - matplotlib
#  - mkl
#  - mkl-include
