[build-system]
requires = [
    "wheel",
    "setuptools",
    "cmake_build_extension",
    "numpy",
    "swig",
    "boost"
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88

[tool.isort]
profile = "black"
multi_line_output = 3