#!/usr/bin/env python3
"""Photon-by-photon Hidden Markov Model (H2MM) engine — self-contained tests.

All tests run on *simulated* data generated by the engine itself, so they need
no external data files.  They check that

* EM recovers the generative model (emission matrix, dwell dynamics),
* the sparse unique-Δt cache reproduces a dense reference on tiny inputs,
* Viterbi returns a valid per-photon path and a finite ICL,
* BIC ranks the true state count best, and
* the BurstFilter / TTTR photon-stream extraction matches a NumPy reference.
"""
import unittest

import numpy as np

import tttrlib


def _simulate(true, seed=1, n_bursts=60, burst_len=300, mean_gap=30):
    rng = np.random.default_rng(seed)
    times = [
        np.cumsum(rng.integers(1, 2 * mean_gap, size=burst_len)).astype(np.int64).tolist()
        for _ in range(n_bursts)
    ]
    streams = tttrlib.HMM.simulate_bursts(true, times, seed + 1)
    return times, [list(s) for s in streams]


class TestHMM(unittest.TestCase):
    def setUp(self):
        # Two clearly separated FRET states, slow dynamics.
        self.true = tttrlib.HmmModel(
            [0.5, 0.5],
            [0.999, 0.001, 0.002, 0.998],
            [0.80, 0.20, 0.25, 0.75],
        )

    def test_model_recovery(self):
        times, streams = _simulate(self.true, seed=2)
        eng = tttrlib.HMM()
        eng.set_bursts(times, streams, 2)
        fit = eng.optimize(tttrlib.HMM.factory_model(2, 2, 1e-3, 0), 300, 1e-9)
        self.assertTrue(fit.converged)
        # Emission matrix recovered up to a possible state relabelling.
        obs = fit.obs_np
        # order states by donor probability so comparison is permutation-free
        order = np.argsort(obs[:, 0])[::-1]
        obs = obs[order]
        np.testing.assert_allclose(obs, self.true.obs_np, atol=0.05)

    def test_squarem_matches_plain_em(self):
        times, streams = _simulate(self.true, seed=3, n_bursts=30)
        eng = tttrlib.HMM()
        eng.set_bursts(times, streams, 2)
        init = tttrlib.HMM.factory_model(2, 2, 1e-3, 5)
        fast = eng.optimize(init, 500, 1e-10, 1e-12, True)
        slow = eng.optimize(init, 500, 1e-10, 1e-12, False)
        # Same EM fixed point (identical log-likelihood), SQUAREM in fewer maps.
        self.assertAlmostEqual(fast.loglik, slow.loglik, delta=1e-3)
        self.assertLessEqual(fast.n_iter, slow.n_iter)

    def test_viterbi_path(self):
        times, streams = _simulate(self.true, seed=4, n_bursts=20)
        eng = tttrlib.HMM()
        eng.set_bursts(times, streams, 2)
        fit = eng.optimize(tttrlib.HMM.factory_model(2, 2, 1e-3, 0), 300, 1e-9)
        path, icl = eng.viterbi_path(fit)
        self.assertEqual(path.shape[0], eng.get_n_photons())
        self.assertTrue(np.isfinite(icl))
        self.assertEqual(set(np.unique(path)).issubset({0, 1}), True)
        self.assertGreater(len(np.unique(path)), 1)  # both states visited

    def test_bic_selects_true_state_count(self):
        times, streams = _simulate(self.true, seed=6, n_bursts=80)
        eng = tttrlib.HMM()
        eng.set_bursts(times, streams, 2)
        bic = {}
        for k in (1, 2, 3):
            fit = eng.fit(k, n_restarts=2, max_iter=300, tol=1e-8, seed=0)
            bic[k] = fit.bic()
        self.assertEqual(min(bic, key=bic.get), 2)

    def test_dense_reference_small(self):
        # On a tiny two-photon-per-burst input the deferred-ρ E-step must match
        # an explicit dense forward-backward.  We check a single EM map's
        # log-likelihood against a brute-force computation.
        prior = np.array([0.6, 0.4])
        A = np.array([[0.9, 0.1], [0.2, 0.8]])
        B = np.array([[0.7, 0.3], [0.3, 0.7]])
        model = tttrlib.HmmModel(list(prior.ravel()), list(A.ravel()), list(B.ravel()))
        times = [[0, 1], [0, 2]]
        streams = [[0, 1], [1, 0]]
        eng = tttrlib.HMM()
        eng.set_bursts(times, streams, 2)
        # engine log-likelihood (one map's E-step value == logL of input model)
        fit = eng.optimize(model, 1, 1e30)  # single map, huge tol -> no convergence loop past 1
        # brute-force logL of the two bursts under (prior, A, B)
        def burst_ll(ts, ss):
            # forward without scaling (tiny)
            n = 2
            alpha = prior * B[:, ss[0]]
            for k in range(1, len(ts)):
                dt = ts[k] - ts[k - 1]
                Adt = np.linalg.matrix_power(A, dt)
                alpha = (alpha @ Adt) * B[:, ss[k]]
            return np.log(alpha.sum())
        ref = burst_ll(times[0], streams[0]) + burst_ll(times[1], streams[1])
        self.assertAlmostEqual(fit.loglik, ref, places=6)

    def test_single_precision_matches_double(self):
        # The approximate float32 fast mode should recover the same model as the
        # exact double path (to within its ~1e-2 log-likelihood round-off).
        times, streams = _simulate(self.true, seed=7, n_bursts=40)
        eng = tttrlib.HMM()
        eng.set_bursts(times, streams, 2)
        init = tttrlib.HMM.factory_model(2, 2, 1e-3, 0)
        exact = eng.optimize(init, 300, 1e-9, 1e-12, True, False)
        fast = eng.optimize(init, 300, 1e-3, 1e-12, True, True)  # single_precision
        ea = exact.obs_np[np.argsort(exact.obs_np[:, 0])]
        fa = fast.obs_np[np.argsort(fast.obs_np[:, 0])]
        np.testing.assert_allclose(ea, fa, atol=0.03)

    def test_burstfilter_extraction_matches_numpy(self):
        # Build a small synthetic TTTR: two channels, a handful of bursts.
        rng = np.random.default_rng(0)
        macro = []
        chan = []
        t = 0
        burst_bounds = []
        for _ in range(15):
            start = len(macro)
            for _ in range(200):
                t += int(rng.integers(1, 20))
                macro.append(t)
                chan.append(0 if rng.random() < 0.6 else 1)
            t += 100000  # long dark gap between bursts
            # Inclusive [start, stop], matching what every TTTR.burst_search*
            # and BurstFilter actually produces: a 30-photon burst comes back as
            # [0, 29]. This test used to build half-open bounds, which agreed
            # with H2MM's own indexing but not with any real burst search --
            # so it passed while H2MM silently dropped each burst's last photon.
            burst_bounds.append((start, len(macro) - 1))
        macro = np.asarray(macro, dtype=np.uint64)
        micro = np.zeros(len(macro), dtype=np.uint16)
        chan = np.asarray(chan, dtype=np.int8)
        evt = np.zeros(len(macro), dtype=np.int8)
        d = tttrlib.TTTR()
        d.append_events(macro, micro, chan, evt, False, 0)

        bursts = np.asarray(burst_bounds, dtype=np.int64)  # (n, 2) [start, stop]

        # C++ extraction
        g = tttrlib.Channel('g'); g.add_component(0, 0, 65535)
        r = tttrlib.Channel('r'); r.add_component(1, 0, 65535)
        eng = tttrlib.HMM()
        eng.set_bursts_from_tttr(d, np.asarray(bursts, dtype=np.int64), [g, r], 3, 1)

        # NumPy reference
        chan_np = np.asarray(d.routing_channels)
        n_ref = sum(int(np.isin(chan_np[s:e + 1], [0, 1]).sum())
                    for s, e in burst_bounds)
        self.assertEqual(eng.get_n_photons(), n_ref)
        self.assertEqual(eng.get_n_bursts(), len(burst_bounds))


if __name__ == '__main__':
    unittest.main()
