name: doc
channels:
    - tpeulen
    - conda-forge
dependencies:
    - tttrlib
    - phconvert
    - doxygen
    - numba
    - scipy
    - pillow
    - sphinx-gallery
    - nbsphinx
    - jupyter_client # needed for nbsphinx
    - tifffile
    - breathe
    - matplotlib
    - numpy
    - numpydoc
    - pyyaml
    - sphinxcontrib-bibtex<2.0.0
    - sphinxcontrib-websupport
    - scikit-image
