name: doc
channels:
    - tpeulen
    - defaults
    - salilab
    - conda-forge
dependencies:
    - tttrlib
    - phconvert
    - doxygen
    - numba
    - scipy
    - pillow
    - sphinx-gallery
    - nbsphinx
    - jupyter_client # needed for nbsphinx
    - tifffile
    - breathe
    - matplotlib
    - numpy
    - numpydoc
    - pyyaml
    - sphinxcontrib-bibtex
    - sphinx-rtd-theme
    - sphinxcontrib-websupport
    - sphinx-bootstrap-theme
