#!/usr/bin/env python
"""
Run all plot_*.py examples in separate subprocesses with a timeout.
Write failing basenames to a blacklist file usable by conf.py.

- Cross-platform (Windows/macOS/Linux)
- Forces headless MPL (MPLBACKEND=Agg)
- Sets TTTRLIB_DOCS=1 so examples can downscale work when building docs
- "Fail" = non-zero exit OR timeout
- By default, removes files from the blacklist when they start succeeding (prune)
"""

from __future__ import annotations
import argparse
import os
import subprocess
import sys
from pathlib import Path
from typing import Iterable, Set


def find_examples(root: Path, pattern: str = "plot_*.py") -> Iterable[Path]:
    yield from (p for p in root.rglob(pattern) if p.is_file())


def load_blacklist(path: Path) -> Set[str]:
    if not path.exists():
        return set()
    names = set()
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        names.add(line)
    return names


def save_blacklist(path: Path, names: Iterable[str]) -> None:
    lines = ["# Auto-generated by run_examples_blacklist.py", "# One basename per line", ""]
    lines.extend(sorted(names))
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def run_one(python_exe: str, script: Path, timeout: int) -> tuple[int, str, str]:
    env = os.environ.copy()
    env.setdefault("MPLBACKEND", "Agg")
    env.setdefault("TTTRLIB_DOCS", "1")  # let examples reduce workload if they wish
    # Use unbuffered -u so we get timely output if needed
    cmd = [python_exe, "-u", str(script)]
    proc = subprocess.Popen(
        cmd, env=env, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True
    )
    try:
        out, err = proc.communicate(timeout=timeout)
        return proc.returncode, out, err
    except subprocess.TimeoutExpired:
        # Hard kill on timeout
        try:
            proc.kill()
        except Exception:
            pass
        try:
            out, err = proc.communicate(timeout=5)
        except Exception:
            out, err = "", ""
        return 124, out, err  # 124 ~ timeout (curl/bash convention)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--examples", default="../examples", help="Path to examples root")
    ap.add_argument("--blacklist", default="gallery_blacklist.txt", help="Blacklist file path")
    ap.add_argument("--timeout", type=int, default=90, help="Per-script timeout (seconds)")
    ap.add_argument("--pattern", default="plot_*.py", help="Glob for examples to run")
    ap.add_argument("--no-prune", action="store_true", help="Do not remove recovered files from blacklist")
    args = ap.parse_args()

    root = Path(args.examples).resolve()
    bl_file = Path(args.blacklist).resolve()

    if not root.exists():
        print(f"[pre-run] Examples dir not found: {root}", file=sys.stderr)
        return 2

    python_exe = sys.executable
    blacklist = load_blacklist(bl_file)

    print(f"[pre-run] Scanning {root} for {args.pattern} ...")
    scripts = list(find_examples(root, args.pattern))
    print(f"[pre-run] Found {len(scripts)} scripts")

    n_ok = n_fail = 0
    newly_failed: Set[str] = set()
    recovered: Set[str] = set()

    for i, script in enumerate(scripts, 1):
        base = script.name
        rel = str(script.relative_to(root))
        print(f"[pre-run {i}/{len(scripts)}] {rel} ... ", end="", flush=True)
        code, out, err = run_one(python_exe, script, args.timeout)

        if code == 0:
            print("OK")
            n_ok += 1
            if not args.no_prune and base in blacklist:
                blacklist.remove(base)
                recovered.add(base)
        else:
            status = "TIMEOUT" if code == 124 else f"FAIL({code})"
            print(status)
            n_fail += 1
            if base not in blacklist:
                newly_failed.add(base)
                blacklist.add(base)

    print(f"\n[pre-run] Summary: OK={n_ok}  FAIL={n_fail}  blacklisted={len(blacklist)}")
    if newly_failed:
        print("[pre-run] Newly blacklisted:")
        for b in sorted(newly_failed):
            print(f"  - {b}")
    if recovered:
        print("[pre-run] Recovered (removed from blacklist):")
        for b in sorted(recovered):
            print(f"  - {b}")

    # Persist blacklist
    save_blacklist(bl_file, blacklist)
    print(f"[pre-run] Wrote blacklist: {bl_file}")

    # Non-zero only if new failures appeared (optional policy); choose 0 to not break CI
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
