python:
  - 2.7
  - 3.7
  - 3.8
pin_run_as_build:
    boost: 
      min_pin: x.x.x
      max_pin: x.x.x
    hdf: 
      min_pin: x.x.x
      max_pin: x.x.x
    fftw:
      min_pin: x.x
      max_pin: x.x
