python:
  - 3.7
swig:
  - 3.0.12
hdf5:
  - 1.10.2                   # [py < 38 and not linux64]
  - 1.10.4                   # [py >= 38 or linux64]
fftw:
  - 3.3.8
boost:
  - 1.67                   # [py < 38]
  - 1.71                   # [py >= 38]
