python:
  - 3.7
hdf5:
  - 1.10.2
  - 1.10.4
fftw:
  - 3.3.8
boost:
  - 1.67.0                     # [py < 38]
  - 1.71.0                     # [py >= 38]
c_compiler:
  - gcc                        # [linux]
  - clang                      # [osx]
  - vs2015                     # [win]
c_compiler_version:            # [unix]
  - 4                          # [osx]
  - 7                          # [linux64 or aarch64]
cxx_compiler:
  - gxx                        # [linux]
  - clangxx                    # [osx]
  - vs2015                     # [win]
cxx_compiler_version:          # [unix]
  - 4                          # [osx]
  - 7                          # [linux64 or aarch64]
