{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
  name: {{ data.get('name')|lower }}
  version: {{ data.get('version')|lower }}

source:
  path: ..

build:
    number: 0
    string: np{{ CONDA_NPY }}py{{ CONDA_PY }}hdf5{{ hdf5 }}

requirements:
  host:
    - python {{ python }}
    - {{ pin_compatible('numpy') }}
    - setuptools
    - git
    - cmake
  build:
    - python {{ python }}
    - {{ pin_compatible('numpy') }}
    - cmake
    - swig 3.0.12.*
    - boost 1.67.0.* # [py < 38]
    - boost 1.71.0.* # [py >= 38]
    - fftw {{ fftw }}
    - hdf5 {{ hdf5 }}
    - llvm-openmp # [osx]
  run:
    - python {{ python }}
    - {{ pin_compatible('numpy') }}
    - hdf5 1.10.2.* # [py < 38 and not linux64]
    - hdf5 1.10.4.* # [py >= 38 or linux64]
    - boost 1.67.0.* # [win]
    - libboost 1.67.0.* # [not win and py < 38]
    - libboost 1.71.0.* # [not win and py >= 38]
    - fftw 3.3.8.*
    - llvm-openmp # [osx]

test:
  imports:
    - tttrlib

about:
  home: https://github.com/fluorescence-tools/tttrlib
  license: {{ data.get('license') }}
  summary: |
    {{ data.get('description') }}
  description: |
    {{ data.get('long_description') }}
  doc_url: https://fluorescence-tools.github.io/tttrlib/

extra:
  recipe-maintainers:
    - tpeulen
