{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
  name: {{ data.get('name')|lower }}
  version: {{ data.get('version')|lower }}

source:
  path: ..

build:
    number: 0
    string: np{{ CONDA_NPY }}py{{ CONDA_PY }}_{{ data.get('GIT_BUILD_STR', "0")|lower }}

requirements:
  host:
    - python {{ python }}
    - {{ pin_compatible('numpy') }}
    - setuptools
    - git
#    - mkl
#    - mkl-include
  build:
    - python {{ python }}
    - {{ pin_compatible('numpy') }}
    - cmake
    - swig 3.0.12.*
    - hdf5 1.10.2.*
    - boost 1.67.0.*
    - libboost 1.67.0.* [not win]
    - fftw
#    - mkl
#    - mkl-include
  run:
    - python {{ python }}
    - {{ pin_compatible('numpy') }}
    - hdf5 1.10.2.*
    - boost 1.67.0.* [win]
    - libboost 1.67.0.* [not win]
    - fftw
#    - mkl

test:
  imports:
    - tttrlib

about:
  home: https://github.com/fluorescence-tools/tttrlib
  license: {{ data.get('license') }}
  summary: Python bindings for tttrlib
  description: |
    tttrlib C++ library including Python wrapper to read time-tagged
    time resolved data files.
  doc_url: https://fluorescence-tools.github.io/tttrlib/

extra:
  recipe-maintainers:
    - tpeulen
