{% set pyproject = load_file_data('../pyproject.toml', from_recipe_dir=True) %}
{% set data = pyproject.get('project', {}) %}

package:
  name: {{ data.get('name') }}
  version: {{ data.get('version') }}

source:
  path: ..

build:
  number: 1
  detect_binary_files_with_prefix: True  # [not win]

requirements:
requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - doxygen
  host:
    - swig <4.3.0
    - boost-cpp
    - hdf5
    - pip
    - python
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - hdf5
    - tqdm
    - click
    - click-didyoumean
    - scikit-image
    - matplotlib-base

test:
 imports:
   - tttrlib
 commands:               # [not win]
   - tttrlib --help      # [not win]

about:
  home: https://github.com/fluorescence-tools/tttrlib
  license: BSD-3-Clause
  summary: |
    {{ data.get('description') }}

extra:
  recipe-maintainers:
    - tpeulen
    - khemmen
