{% set name = "tttrlib" %}
#{% set version = "0.0.11" %}
{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
  name: "{{ name|lower }}"
  version: {{ data.get('version')|lower }}
  #  version: "{{ version|lower }}"

source:
  path: ..

build:
    number: 0
    string: np{{ CONDA_NPY }}py{{ CONDA_PY }}_{{ GIT_BUILD_STR }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - python {{ python }}
    - {{ pin_compatible('numpy') }}
    - git
    - cmake
    - swig
    - doxygen
    - setuptools
    - hdf5=1.10.5
    - boost
  host:
    - python {{ python }}
    - {{ pin_compatible('numpy') }}
    - setuptools
  run:
    - python {{ python }}
    - {{ pin_compatible('numpy') }}
    - hdf5=1.10.5
    - boost

test:
  imports:
    - tttrlib

about:
  home: https://github.com/fluorescence-tools/tttrlib
  license: MPL 2.0
  summary: Python bindings for tttrlib
  description: |
    tttrlib C++ library including Python wrapper to read time-tagged
    time resolved data files.
  doc_url: https://fluorescence-tools.github.io/tttrlib/

extra:
  recipe-maintainers:
    - tpeulen
