package:
  name: tttrlib
  version: {{ environ.get('GIT_DESCRIBE_NUMBER', 'default')}}

source:
  git_url: ../../CLionProjects/tttrlib
  #path: ../../CLionProjects/tttrlib/

requirements:
  build:
    - python {{ python }}
    - setuptools
    - numpy
    - swig
    - hdf5
    - cmake
  host:
    - python {{ python }}
    - numpy
    - hdf5
  run:
    - numpy
    - python {{ python }}
    - hdf5
    
#outputs:
#    - type: wheel
#    - name: tttrlib

test:
  imports:
    - tttrlib

about:
  home: https://github.com/tpeulen/tttrlib
  license: MPL-2.0
  summary: Python bindings for tttrlib
  description: |
    tttrlib C++ library including Python wrapper to read time-tagged
    time resolved data files.
