{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
  name: {{ data.get('name')|lower }}
  version: {{ data.get('version')|lower }}

source:
#  path: ..
  git_url: ..

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python {{ python }}
    - setuptools
    - numpy
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - pkg-config   # [not win]
    - boost-cpp
    - hdf5
    - fftw
    - swig
    - cmake
    - make         # [linux]
  run:
    - python
    - typing [py27]
    - {{ pin_compatible('numpy') }}
    - boost-cpp
    - hdf5
    - fftw
    - llvm-openmp # [osx]

about:
  home: https://github.com/fluorescence-tools/tttrlib
  license: {{ data.get('license') }}
  summary: |
    {{ data.get('description') }}
description: |
    {{ data.get('long_description') }}

extra:
  recipe-maintainers:
    - tpeulen
