{% set pyproject = load_file_data('../pyproject.toml', from_recipe_dir=True) %}
{% set data = pyproject.get('project', {}) %}

package:
  name: {{ data.get('name') }}
  version: {{ data.get('version') }}

source:
  path: ..

build:
  number: 1
  detect_binary_files_with_prefix: True  # [not win]
  run_exports: '{{ pin_subpackage("tttrlib", max_pin="x.x") }}'

requirements:
requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config # [not win]
    - cmake
    - ninja
    - make # [not win]
  host:
    - swig <4.3.0
    - doxygen
    - llvm-openmp   # [osx]
    - libgomp   # [linux]
    - boost-cpp
    - hdf5
    - python
    - pip
    - numpy
  run:
    - python
    - llvm-openmp   # [osx]
    - libgomp   # [linux]
    - boost-cpp
    - tqdm
    - numpy
    - click
    - click-didyoumean
    - scikit-image
    - matplotlib-base
    - hdf5

test:
 imports:
   - tttrlib
 commands:               # [not win]
   - tttrlib --help      # [not win]

about:
  home: https://github.com/fluorescence-tools/tttrlib
  summary: 'A file format agnostic library for time-resolved imaging and spectroscopic data.'
  description: |
    tttrlib is a simple, fast, libray to read, write and process
    time-resolved imaging and spectroscopic data. For speed, it 
    is written in C++ and wrapped for Python via SWIG.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: https://tttrlib.readthedocs.io
  dev_url: https://github.com/fluorescence-tools/tttrlib

extra:
  recipe-maintainers:
    - tpeulen
    - khemmen