{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}
{% set PY_VER_MAJOR = PY_VER[0] %}
{% set PY_VER_MINOR = PY_VER[2] %}

# This conda recipe makes sure that hdf5 and boost is linked as in version(IMP) <= 2.14
# Later IMP versions use more generic linking and should work with meta.yaml

package:
  name: {{ data.get('name')|lower }}
  version: {{ data.get('version')|lower }}

source:
#  path: ..
  git_url: ..

build:
    number: 0
    string: py{{ PY_VER_MAJOR }}{{ PY_VER_MINOR }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python {{ python }}
    - setuptools
    - doxygen
    - cmake
    - swig
    - numpy
    - fftw
    - pkg-config
    - boost {{ boost }}
    - hdf5 {{ hdf5 }}
  host:
    - python
    - numpy
    - boost
    - hdf5
    - fftw
  run:
    - python
    - typing [py27]
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('boost', max_pin='x.x.x') }}
    - {{ pin_compatible('hdf5', max_pin='x.x.x') }}
    - {{ pin_compatible('fftw', max_pin='x.x') }}
    - llvm-openmp # [osx]

test:
 imports:
   - tttrlib

about:
  home: https://github.com/fluorescence-tools/tttrlib
  license: {{ data.get('license') }}
  summary: |
    {{ data.get('description') }}
  description: |
    {{ data.get('long_description') }}

extra:
  recipe-maintainers:
    - tpeulen
