package:
  name: tttrlib
  #version: {{ environ.get('GIT_DESCRIBE_NUMBER', 'default')}}
  version: 0.0.6

source:
  #git_url: ..
  path: ..

requirements:
  build:
    - python {{ python }}
    - setuptools
    - numpy
    - swig
    - hdf5
    - cmake
    - sphinx
  host:
    - python {{ python }}
    - numpy
    - sphinx
    - hdf5
  run:
    - numpy
    - python {{ python }}
    - hdf5
    
#outputs:
#    - type: wheel
#    - name: tttrlib

test:
  imports:
    - tttrlib

about:
  home: https://github.com/tpeulen/tttrlib
  license: Mozilla Public License 2.0 (MPL 2.0)
  summary: Python bindings for tttrlib
  description: |
    tttrlib C++ library including Python wrapper to read time-tagged
    time resolved data files.
