{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
  name: {{ data.get('name')|lower }}
  version: 0.21.0 #{{ data.get('version')|lower }}

source:
#  path: ..
  git_url: ../

build:
    number: 0
    string: py{{ CONDA_PY }}np{{ numpy }}boost{{ boost }}hdf5{{ hdf5 }}

requirements:
  host:
    - python {{ python }}.*
    - numpy {{ numpy }}.*
    - setuptools
  build:
    - python {{ python }}.*
    - numpy {{ numpy }}.*
  run:
    - python {{ python }}.*

test:
  imports:
    - tttrlib

about:
  home: https://github.com/fluorescence-tools/tttrlib
  license: {{ data.get('license') }}
  summary: |
    {{ data.get('description') }}
  description: |
    {{ data.get('long_description') }}
  doc_url: https://fluorescence-tools.github.io/tttrlib/

extra:
  recipe-maintainers:
    - tpeulen
