{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}
{% set PY_VER_MAJOR = PY_VER[0] %}
{% set PY_VER_MINOR = PY_VER[2] %}

package:
  name: {{ data.get('name')|lower }}
  version: {{ data.get('version')|lower }}

source:
#  path: ..
  git_url: ..

build:
    number: 0
    string: py{{ PY_VER_MAJOR }}{{ PY_VER_MINOR }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}

requirements:
  host:
    - python {{ python }}
    - numpy
    - setuptools
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.13
    - pathlib2 [py27]
    - python {{ python }}
    - numpy
    - swig
    - boost 1.67.0.* [py < 38]
    - boost 1.71.0.* [py >= 38]
    - hdf5 1.10.2.* [py < 38 and not linux64]
    - hdf5 1.10.4.* [py >= 38 or linux64]
    - fftw 3.3.4.* [win]
    - fftw 3.3.8.* [not win]
    - llvm-openmp [osx]
  run:
    - python {{ python }}
    - numpy
    - boost 1.67.0.* [py < 38]
    - boost 1.71.0.* [py >= 38]
    - libboost 1.71.0.* [py >= 38]
    - libboost 1.67.0.* [py < 38]
    - hdf5 1.10.2.* [py < 38 and not linux64]
    - hdf5 1.10.4.* [py >= 38 or linux64]
    - fftw 3.3.4.* [win]
    - fftw 3.3.8.* [not win]
    - llvm-openmp [osx]

#test:
#  imports:
#    - tttrlib

about:
  home: https://github.com/fluorescence-tools/tttrlib
  license: {{ data.get('license') }}
  summary: |
    {{ data.get('description') }}
  description: |
    {{ data.get('long_description') }}

extra:
  recipe-maintainers:
    - tpeulen
