{% set pyproject = load_file_data('../pyproject.toml', from_recipe_dir=True) %}
{% set data = pyproject.get('project', {}) %}

package:
  name: {{ data.get('name') }}
  version: {{ data.get('version') }}

source:
  path: ../
#  git_url: ..

build:
  number: 1
  detect_binary_files_with_prefix: True  # [not win]

requirements:
  build:
    - python
    - numpy
    - doxygen
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - pkg-config   # [not win]
    - swig
    - ninja
    - cmake
    - make         # [linux]
  host:
    - boost-cpp
    - hdf5
    - python
    - setuptools
    - numpy
  run:
    - python
    - tqdm
    - click
    - click-didyoumean
    - {{ pin_compatible('numpy') }}
    - scikit-image
    - matplotlib
    - hdf5

test:
 imports:
   - tttrlib
 commands:            # [not win]
   - tttrlib --help   # [not win]

about:
  home: https://github.com/fluorescence-tools/tttrlib
  license: BSD-3
  summary: |
    {{ data.get('description') }}

extra:
  recipe-maintainers:
    - tpeulen
