{% set pyproject = load_file_data('../pyproject.toml', from_recipe_dir=True) %}
{% set data = pyproject.get('project', {}) %}

package:
  name: {{ data.get('name') }}
  version: {{ data.get('version') }}

source:
  path: ../
#  git_url: ..

build:
  number: 1
  detect_binary_files_with_prefix: True  # [not win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp        # [osx]
    - libgomp            # [linux]
    - pkg-config         # [not win]
    - cmake
    - ninja
    - make               # [linux]
    - doxygen
    - swig
    - python
    - numpy
    - typing             # [py27]
  host:
    - libboost-devel
    - hdf5
    - python
    - setuptools
    - typing             # [py27]
    - numpy
  run:
    - python
    - tqdm               # [py > 27]
    - tqdm <=4.14        # [py27]    
    - click
    - click-didyoumean
    - {{ pin_compatible('numpy') }}
    - scikit-image
    - matplotlib-base
    - hdf5
    - typing             # [py27]
    - importlib_metadata # [py27]

test:
 imports:
   - tttrlib
 commands:               # [not win]
   - tttrlib --help      # [not win]

about:
  home: https://github.com/fluorescence-tools/tttrlib
  license: BSD-3-Clause
  summary: |
    {{ data.get('description') }}

extra:
  recipe-maintainers:
    - tpeulen
