// SPDX-License-Identifier: BSD-3-Clause
//
// tttrlib for Node.js.
//
// This file is the JavaScript counterpart of the ext/python/*.py helpers that
// Python's binding injects with %pythoncode. The native addon (tttrlib.node) is
// generated by SWIG from the same interface fragments as the Python, R and Java
// bindings, so it already exposes the whole C++ surface with the C++ names. What
// it does not do is make that surface read like JavaScript, and Python's binding
// solves the same problem the same way -- in a scripting layer on top:
//
//   * camelCase aliases beside the C++ snake_case names (both work);
//   * properties for `get_x()` / `set_x(v)` pairs, which is what Python's
//     TTTR.__getattr__ does;
//   * registry() and the other JSON entry points parsed into objects;
//   * the handful of helpers whose Python versions are pure Python
//     (read_csv, SimEngine.from_dict, TTTR slicing).
//
// Nothing here reimplements analysis. Anything that computes lives in C++, so
// the numbers cannot drift from the other bindings.

'use strict';

const path = require('path');
const fs = require('fs');

// ---------------------------------------------------------------------------
// Load the addon
// ---------------------------------------------------------------------------
// Search order: next to this file (the npm package layout and the CMake
// js-pkg/ staging directory), then a couple of build-tree locations so a
// developer can `require()` straight out of a build without installing.
function loadAddon() {
  const candidates = [
    path.join(__dirname, 'tttrlib.node'),
    path.join(__dirname, 'build', 'Release', 'tttrlib.node'),
  ];

  // Any build*/js-pkg/ at the repository root, so `cmake -B build`,
  // `-B build-js`, `-B build-debug` and the like all work without configuration.
  // Sorted newest first: a developer with several build trees means the one just
  // built, not whichever the directory listing happens to return first.
  const repoRoot = path.join(__dirname, '..', '..', '..');
  try {
    const builds = fs.readdirSync(repoRoot, { withFileTypes: true })
      .filter((e) => e.isDirectory() && /^(build|cmake-build)/.test(e.name))
      .map((e) => path.join(repoRoot, e.name, 'js-pkg', 'tttrlib.node'))
      .filter((p) => fs.existsSync(p))
      .sort((a, b) => fs.statSync(b).mtimeMs - fs.statSync(a).mtimeMs);
    candidates.push(...builds);
  } catch { /* not in a source tree: the installed layout above is enough */ }

  if (process.env.TTTRLIB_ADDON) candidates.unshift(process.env.TTTRLIB_ADDON);

  const tried = [];
  for (const c of candidates) {
    if (fs.existsSync(c)) return require(c);
    tried.push(c);
  }
  throw new Error(
    'tttrlib: native addon not found. Looked in:\n  ' + tried.join('\n  ') +
    '\nBuild it with `cmake -DBUILD_JAVASCRIPT_INTERFACE=ON` or set TTTRLIB_ADDON.');
}

const native = loadAddon();

// ---------------------------------------------------------------------------
// snake_case -> camelCase, without losing the original names
// ---------------------------------------------------------------------------
const camel = (s) => s.replace(/_([a-z0-9])/g, (_, c) => c.toUpperCase());

// Own + inherited enumerable and non-enumerable names on a prototype chain,
// stopping at Object.prototype. SWIG puts methods on the prototype as
// non-enumerable accessors, so Object.keys() alone would see nothing.
function protoNames(proto) {
  const out = new Set();
  for (let p = proto; p && p !== Object.prototype; p = Object.getPrototypeOf(p)) {
    for (const k of Object.getOwnPropertyNames(p)) out.add(k);
  }
  return out;
}

// Add `foo()` alongside `get_foo()`, and a `foo` property when there is a
// getter -- the JavaScript form of Python's TTTR.__getattr__ trick, which turns
// `t.get_macro_times()` into `t.macroTimes`. Both spellings stay callable: a
// script ported from Python keeps working, and so does one written against the
// C++ documentation.
// Find a property's descriptor anywhere on the prototype chain. A method
// inherited from a base class has no OWN descriptor on the derived prototype,
// and looking only one level up misses anything deeper.
function findDescriptor(proto, name) {
  for (let p = proto; p && p !== Object.prototype; p = Object.getPrototypeOf(p)) {
    const d = Object.getOwnPropertyDescriptor(p, name);
    if (d) return d;
  }
  return undefined;
}

function decorate(proto) {
  const names = protoNames(proto);
  for (const name of names) {
    if (name === 'constructor') continue;

    const alias = camel(name);
    if (alias !== name && !names.has(alias)) {
      const d = findDescriptor(proto, name);
      if (d) Object.defineProperty(proto, alias, d);
    }

    // get_x / set_x -> a real property `x` (and its camelCase spelling).
    //
    // A `get_x` that needs arguments becomes a property whose access throws.
    // There is no way to tell from here -- a SWIG-generated Napi::Function
    // reports length 0 whatever its C++ arity -- and Python's __getattr__ has
    // exactly the same behaviour, so this matches the reference binding rather
    // than inventing a different one. Call the method when it takes arguments.
    const m = /^get_(.+)$/.exec(name);
    if (!m) continue;
    const bare = m[1];
    const setter = names.has('set_' + bare) ? 'set_' + bare : null;
    for (const propName of new Set([bare, camel(bare)])) {
      if (names.has(propName) || names.has('get_' + propName)) continue;
      const spec = {
        configurable: true,
        get() { return this[name](); },
      };
      if (setter) spec.set = function (v) { this[setter](v); };
      try { Object.defineProperty(proto, propName, spec); } catch (_) { /* frozen: skip */ }
    }
  }
}

const exported = {};
// getOwnPropertyNames, not keys: SWIG defines the module's classes and functions
// with napi_define_properties, which does not mark them enumerable, so
// Object.keys() sees an empty module.
for (const key of Object.getOwnPropertyNames(native)) {
  const v = native[key];
  exported[key] = v;
  if (typeof v === 'function' && v.prototype) decorate(v.prototype);
  const alias = camel(key);
  if (alias !== key && !(alias in native)) exported[alias] = v;
}

// ---------------------------------------------------------------------------
// registry() -- the JSON entry points, parsed
// ---------------------------------------------------------------------------
// Same contract as Python's tttrlib.registry(): no category returns every
// category, a category returns its entries, an unknown category throws and
// names the ones that exist. A UI built on this has no hard-coded algorithm
// list, which is the whole reason the registry exists.
function registry(category) {
  // The category list comes from the parsed JSON rather than from
  // registry_categories(), for the same reason Python's registry() documents:
  // the JSON is the single source of truth either way, and one parse answers
  // both questions.
  const everything = JSON.parse(native.registry_json());
  if (category === undefined || category === null) return everything;
  if (!(category in everything)) {
    throw new Error(
      `unknown registry category '${category}'; ` +
      `available: ${Object.keys(everything).sort().join(', ')}`);
  }
  return everything[category];
}

const jsonEntryPoints = {
  fitModels: 'fit_models_json',
  fitSetup: 'fit_setup_json',
  fitObjectives: 'fit_objectives_json',
};
for (const [name, fn] of Object.entries(jsonEntryPoints)) {
  if (typeof native[fn] === 'function') {
    exported[name] = () => JSON.parse(native[fn]());
  }
}

// ---------------------------------------------------------------------------
// TTTR conveniences
// ---------------------------------------------------------------------------
if (native.TTTR) {
  const P = native.TTTR.prototype;

  // The C++ accessors are singular (get_routing_channel, get_event_type) but
  // return one value PER EVENT, so Python's TTTR.py exposes them under plural
  // names. Match that: `tttr.routingChannels` should not be a different
  // spelling from one binding to the next.
  Object.defineProperty(P, 'routingChannels', {
    configurable: true, get() { return this.get_routing_channel(); },
  });
  Object.defineProperty(P, 'routing_channels', {
    configurable: true, get() { return this.get_routing_channel(); },
  });
  Object.defineProperty(P, 'eventTypes', {
    configurable: true, get() { return this.get_event_type(); },
  });
  Object.defineProperty(P, 'event_types', {
    configurable: true, get() { return this.get_event_type(); },
  });

  // Python: TTTR.acquisition_time
  Object.defineProperty(P, 'acquisitionTime', {
    configurable: true,
    get() {
      const t = this.get_macro_times();
      if (t.length === 0) return 0;
      // BigInt subtraction keeps full precision; the resolution scaling is the
      // only place a double is unavoidable, and by then the difference is small.
      const span = t[t.length - 1] - t[0];
      // %attribute exposes the resolution as a property, not a getter.
      return Number(span) * this.get_header().macro_time_resolution;
    },
  });

  // Python: len(tttr) and tttr[key]
  P.length = function () { return this.get_n_valid_events(); };

  // Python: tttr[slice-or-index-array] -> a new TTTR over those events.
  P.select = function (sel) {
    let idx;
    if (sel instanceof Int32Array) {
      idx = sel;
    } else if (Array.isArray(sel)) {
      idx = Int32Array.from(sel);
    } else if (typeof sel === 'number') {
      idx = Int32Array.of(sel);
    } else if (sel && typeof sel === 'object' && 'start' in sel) {
      const n = this.get_n_valid_events();
      const start = sel.start ?? 0;
      const stop = sel.stop ?? n;
      const step = sel.step ?? 1;
      const out = [];
      for (let i = start; step > 0 ? i < stop : i > stop; i += step) out.push(i);
      idx = Int32Array.from(out);
    } else {
      throw new TypeError('select() takes an index, an array of indices, ' +
                          'an Int32Array, or {start, stop, step}');
    }
    return new native.TTTR(this, idx);
  };

  // Python: tttr + other
  P.concat = function (other) {
    const t = new native.TTTR(this);
    t.append(other);
    return t;
  };

  // Registry-driven burst search, exactly as Python's burst_search_by_name:
  // the algorithm list and every parameter default come from the registry, so
  // adding a search to tttrlib adds it here with no change to this file.
  P.burstSearchByName = function (algorithm, parameters = {}) {
    const entries = registry('burst_search');
    const entry = entries[algorithm];
    if (!entry) {
      throw new Error(
        `unknown burst search '${algorithm}'; available: ${Object.keys(entries).join(', ')}`);
    }
    const props = (entry.params_schema && entry.params_schema.properties) || {};
    const unknown = Object.keys(parameters).filter((k) => !(k in props));
    if (unknown.length) {
      throw new Error(
        `unknown parameter(s) for '${algorithm}': ${unknown.join(', ')}; ` +
        `accepted: ${Object.keys(props).join(', ')}`);
    }
    // Positional call in schema order, defaults filled from the schema -- the
    // C++ methods take positional arguments and JavaScript has no **kwargs.
    const args = Object.keys(props).map((k) =>
      (k in parameters) ? parameters[k] : props[k].default);
    // An entry's `method` may be implemented in C++ or, for a composition like
    // the coincident search, in this scripting layer -- which is also where
    // Python implements it. Accept the C++ spelling and the camelCase alias.
    const fn = this[entry.method] ?? this[camel(entry.method)];
    if (typeof fn !== 'function') {
      throw new Error(
        `registry names method '${entry.method}', which this build does not expose`);
    }
    return fn.apply(this, args);
  };

  /**
   * Bursts that appear in several detector groups at once.
   *
   * A burst search over the pooled photon stream cannot tell a molecule
   * carrying every label from one carrying a subset: both are simply bright.
   * Requiring the burst to be found *independently* in more than one group of
   * detectors can — it is what rejects singly-labelled and photobleached
   * molecules in ALEX/PIE.
   *
   * Coincidence is decided in TIME, not per photon: a burst found in one group
   * marks the whole span of photons it covers, so photons belonging to other
   * groups fall inside it, and a photon is coincident when at least
   * `minGroups` groups mark it.
   *
   * This is a composition, not an algorithm: the search named by `algorithm`
   * runs once per group, so it works with every registry entry, including ones
   * added later. It lives here rather than in C++ because it does in Python
   * too — `ext/python/TTTR.py` — and the two implementations must agree, which
   * is easiest when they are the same twenty lines.
   *
   * @returns flat [start, stop, start, stop, ...] inclusive photon indices,
   *          the same convention as every other burst search.
   */
  // Positional, in the registry's schema order and matching Python's
  // burst_search_coincident signature exactly -- so the generic dispatcher below
  // can call it like any other entry, and a script ported from Python still
  // reads the same.
  P.burstSearchCoincident = function (
    channelGroups, algorithm = 'maxtree', minGroups = 0, L = 20, parameters = null) {
    const groups = Array.from(channelGroups, (g) => Array.from(g, Number));
    if (groups.length === 0) throw new Error('channelGroups is empty');

    const channels = this.get_routing_channel();
    const votes = new Int32Array(channels.length);

    let nUsed = 0;
    for (const group of groups) {
      const wanted = new Set(group);
      const member = [];
      for (let i = 0; i < channels.length; i++) if (wanted.has(channels[i])) member.push(i);
      if (member.length === 0) continue;   // a group with no photons cannot vote
      nUsed++;
      const idx = Int32Array.from(member);
      const bursts = new native.TTTR(this, idx).burstSearchByName(algorithm, parameters || {});
      for (let b = 0; b < bursts.length; b += 2) {
        // Sub-indices map back through `member`; marking the enclosed GLOBAL
        // range is what makes the coincidence temporal rather than per photon.
        const first = member[Number(bursts[b])];
        const last = member[Number(bursts[b + 1])];
        for (let i = first; i <= last; i++) votes[i]++;
      }
    }

    if (nUsed === 0) {
      const used = Array.from(new Set(channels)).sort((a, b) => a - b);
      throw new Error(
        `no channel group contains photons; used routing channels are ${used.join(', ')}`);
    }
    const required = minGroups ? Number(minGroups) : nUsed;
    if (required > nUsed) {
      throw new Error(`minGroups=${required} exceeds the ${nUsed} group(s) containing photons`);
    }

    // Run-length encode the coincident mask into inclusive intervals.
    const out = [];
    let start = -1;
    for (let i = 0; i <= votes.length; i++) {
      const inRun = i < votes.length && votes[i] >= required;
      if (inRun && start < 0) start = i;
      else if (!inRun && start >= 0) {
        if (i - start >= Number(L)) out.push(BigInt(start), BigInt(i - 1));
        start = -1;
      }
    }
    return BigInt64Array.from(out);
  };

  /** Names of the burst searches this build offers. Never hard-code this list. */
  exported.burstSearchAlgorithms = () => Object.keys(registry('burst_search'));

  /** Default parameters of one burst search, as an object. */
  exported.burstSearchDefaults = (algorithm) => {
    const entry = registry('burst_search')[algorithm];
    if (!entry) throw new Error(`unknown burst search '${algorithm}'`);
    const props = (entry.params_schema && entry.params_schema.properties) || {};
    return Object.fromEntries(Object.entries(props).map(([k, v]) => [k, v.default]));
  };
}

// ---------------------------------------------------------------------------
// TTTRHeader: the JSON payload as an object
// ---------------------------------------------------------------------------
if (native.TTTRHeader) {
  const P = native.TTTRHeader.prototype;
  Object.defineProperty(P, 'json', {
    configurable: true,
    get() { return this.get_json(); },
    set(v) { this.set_json(typeof v === 'string' ? v : JSON.stringify(v)); },
  });
  /** The header's tags as a plain object (Python: header.tags). */
  P.tags = function () {
    const j = JSON.parse(this.get_json());
    return j.tags ?? j;
  };
}

// ---------------------------------------------------------------------------
// Tabular I/O -- the Python versions of these are also pure scripting layer
// ---------------------------------------------------------------------------
// A SWIG std::vector<std::string> parameter will not take a JavaScript array:
// the typemap wants the wrapped type. Both CSV entry points below have list
// options, so the conversion lives here once.
function vectorString(values) {
  const v = new native.VectorString();
  for (const s of values) v.add(String(s));
  return v;
}

if (typeof native.read_csv_into === 'function' && native.CsvOptions) {
  /**
   * Read a CSV into a DataStore, in parallel, without an intermediate copy.
   * Mirrors Python's tttrlib.read_csv().
   */
  exported.readCsv = function (filename, opts = {}) {
    const o = new native.CsvOptions();
    if (opts.delimiter !== undefined) o.delimiter = opts.delimiter;
    if (opts.quote !== undefined) o.quote = opts.quote;
    if (opts.hasHeader !== undefined) o.has_header = opts.hasHeader;
    if (opts.useFloat32 !== undefined) o.use_float32 = opts.useFloat32;
    if (opts.threads !== undefined) o.threads = opts.threads | 0;
    if (opts.blockSize !== undefined) o.block_size = opts.blockSize | 0;
    if (opts.newlinesInValues !== undefined) o.newlines_in_values = opts.newlinesInValues;
    if (opts.naValues !== undefined) o.na_values = vectorString(opts.naValues);
    if (opts.textColumns !== undefined) o.force_text_columns = vectorString(opts.textColumns);
    const store = new native.DataStore();
    native.read_csv_into(store, filename, o);
    return store;
  };
}

if (typeof native.write_csv === 'function' && native.CsvWriteOptions) {
  /**
   * Write a DataStore as CSV. Mirrors Python's tttrlib.write_csv().
   * Pass null as the filename to get the text back instead of a file.
   */
  exported.writeCsv = function (filename, store, opts = {}) {
    const o = new native.CsvWriteOptions();
    if (opts.delimiter !== undefined) o.delimiter = opts.delimiter;
    if (opts.quote !== undefined) o.quote = opts.quote;
    if (opts.header !== undefined) o.has_header = opts.header;
    if (opts.quoting !== undefined) {
      const q = {
        needed: native.CsvQuoting_Needed,
        all: native.CsvQuoting_All,
        none: native.CsvQuoting_Never,
      };
      o.quoting = typeof opts.quoting === 'string' ? q[opts.quoting] : opts.quoting;
    }
    if (opts.eol !== undefined) o.eol = opts.eol;
    if (opts.naRep !== undefined) o.null_string = opts.naRep;
    if (opts.trueString !== undefined) o.true_string = opts.trueString;
    if (opts.falseString !== undefined) o.false_string = opts.falseString;
    if (opts.floatPrecision !== undefined) o.float_precision = opts.floatPrecision | 0;
    if (opts.floatDecimals !== undefined) o.float_decimals = opts.floatDecimals | 0;
    if (opts.keepDecimalPoint !== undefined) o.keep_decimal_point = opts.keepDecimalPoint;
    if (opts.selectedOnly !== undefined) o.selected_only = opts.selectedOnly;
    if (opts.columns !== undefined) o.columns = vectorString(opts.columns);
    if (opts.threads !== undefined) o.threads = opts.threads | 0;
    if (opts.blockRows !== undefined) o.block_rows = opts.blockRows | 0;
    if (filename === null || filename === undefined) return native.write_csv_string(store, o);
    if (!native.write_csv(filename, store, o)) throw new Error(`write_csv: could not write ${filename}`);
    return true;
  };
}

if (typeof native.read_hdf5_table_into === 'function') {
  /** Read a columnar HDF5 table into a DataStore. Mirrors Python's read_hdf5(). */
  exported.readHdf5 = function (filename, group = '/') {
    const store = new native.DataStore();
    // Filled in place: returning by value would copy the whole table at the
    // moment it is largest.
    native.read_hdf5_table_into(store, filename, group);
    return store;
  };
}
if (typeof native.write_hdf5_table === 'function') {
  /**
   * Write a DataStore as a columnar HDF5 table. Mirrors Python's write_hdf5().
   *
   * Writing a group replaces that group and everything under it; under the
   * default Update mode every other group in the file is left alone. Writing
   * '/' replaces the file's whole content. A file that exists and is not HDF5
   * is refused rather than replaced -- pass Hdf5WriteMode_Truncate for that.
   */
  exported.writeHdf5 = (filename, store, group = '/', compression = 0, mode = undefined) =>
    native.write_hdf5_table(filename, store, group, compression,
                            mode === undefined ? native.Hdf5WriteMode_Update : mode);
}

// ---------------------------------------------------------------------------
// Simulator: the object/JSON entry point (Python: SimEngine.from_dict)
// ---------------------------------------------------------------------------
if (native.SimEngine && typeof native.SimEngine.from_json === 'function') {
  /** Build a SimEngine from a config object, following examples/simulation/sim.schema.json. */
  native.SimEngine.fromObject = (config) => native.SimEngine.from_json(JSON.stringify(config));
}

// ---------------------------------------------------------------------------
// Analysis conveniences: the JavaScript half of the %pythoncode blocks
// ---------------------------------------------------------------------------
//
// Python gets these from `%pythoncode` in the shared .i files, which no other
// backend reaches. The C++ underneath is wrapped for JavaScript already -- what
// was missing is the same shorthand, so a caller had to know that a simulated
// photon stream is seven parallel accessors rather than one call.
//
// Each is written against the same C++ the Python version calls, so the two
// answer identically by construction rather than by coincidence.

if (native.SimEngine) {
  /**
   * The photon stream as an object of typed arrays -- the counterpart of
   * Python's SimEngine.photons().
   *
   * Without this the simulator can be run but not read: the seven channels are
   * separate accessors, and nothing said they were parallel arrays over the
   * same events.
   *
   * @returns {{macroWindow, arrivalTime, channel, microTime, species, molecule, eventType}}
   *   `species === n_species` marks background; `eventType` is 0 for a photon
   *   and 1 for a marker.
   */
  native.SimEngine.prototype.photons = function () {
    return {
      macroWindow: this.macro_window(),
      arrivalTime: this.arrival_time(),
      channel: this.channel(),
      microTime: this.micro_time(),
      species: this.emitting_species(),
      molecule: this.emitting_molecule(),
      eventType: this.event_type(),
    };
  };
}

// BVA and TwoCDE both derive from BurstFeature, so `result` is defined once on
// each -- the prototype chain SWIG builds does not always carry it across.
for (const cls of ['BVA', 'TwoCDE', 'BurstFeatureExtractor']) {
  const C = native[cls];
  if (!C || typeof C.prototype.get_result !== 'function') continue;
  /** Per-burst feature value, NaN where undefined. Python: `.result`. */
  Object.defineProperty(C.prototype, 'result', {
    get() { return this.get_result(); },
    configurable: true,
  });
}

if (native.BVA) {
  /** Per-burst mean proximity ratio. Python: `.proximity_ratio_mean`. */
  Object.defineProperty(native.BVA.prototype, 'proximityRatioMean', {
    get() { return this.get_proximity_ratio_mean(); },
    configurable: true,
  });
  /** Per-burst proximity-ratio standard deviation. */
  Object.defineProperty(native.BVA.prototype, 'proximityRatioStd', {
    get() { return this.get_proximity_ratio_std(); },
    configurable: true,
  });
}

if (native.TwoCDE) {
  /** Per-burst 2CDE value, NaN where undefined. Python: `.two_cde`. */
  Object.defineProperty(native.TwoCDE.prototype, 'twoCde', {
    get() { return this.get_result(); },
    configurable: true,
  });
}

if (native.HMM) {
  /**
   * Per-photon Viterbi state path and its ICL score.
   * @returns {{path, icl: number}}
   */
  native.HMM.prototype.viterbiPath = function (model) {
    const [path, icl] = this.viterbi(model);
    return { path, icl: Number(icl) };
  };

  /**
   * Per-photon posterior state probabilities -- a distribution over states for
   * each photon, not the winner-takes-all assignment Viterbi reports.
   * @returns {{gamma, nUnderflow: number}}
   */
  native.HMM.prototype.gamma = function (model) {
    const [g, nUnderflow] = this.posterior(model);
    return { gamma: g, nUnderflow: Number(nUnderflow) };
  };

  /**
   * Draw each photon's state independently from its gamma row. Faithful per
   * photon, but the draws are independent so the path fragments -- use
   * ffbsPaths() for dwell times or transition counts.
   * @returns {{path, nUnderflow: number}}
   */
  native.HMM.prototype.jitterPath = function (model, seed = 0) {
    const [path, nUnderflow] = this.sample_states(model, seed);
    return { path, nUnderflow: Number(nUnderflow) };
  };

  /** Whole trajectories drawn from P(path | data), by forward-backward sampling. */
  native.HMM.prototype.ffbsPaths = function (model, seed = 0, nSamples = 1) {
    return this.sample_paths(model, seed, nSamples);
  };
}

if (native.NeuralNet) {
  /** The weight matrix of layer `i`, as rows of n_in. Python: `layer_weights(i)`. */
  native.NeuralNet.prototype.layerWeights = function (i) {
    const layer = this.get_layers().get(i);
    const flat = layer.weight;
    const nIn = Number(layer.n_in);
    const rows = [];
    for (let r = 0; r < Number(layer.n_out); r++) {
      rows.push(Float64Array.from(flat.slice(r * nIn, (r + 1) * nIn)));
    }
    return rows;
  };

  /** The bias vector of layer `i`. Python: `layer_bias(i)`. */
  native.NeuralNet.prototype.layerBias = function (i) {
    return this.get_layers().get(i).bias;
  };
}

// ---------------------------------------------------------------------------
exported.registry = registry;

/**
 * True when array results are zero-copy views over C++ memory. False means the
 * host declined external ArrayBuffers (Electron, V8-sandbox builds) or the addon
 * was compiled with -DTTTRLIB_JS_COPY_ARRAYS, and every array is a copy.
 */
exported.arraysAreZeroCopy = native.arraysAreZeroCopy;

/** The underlying SWIG addon, for anything this layer does not cover. */
exported.native = native;

module.exports = exported;
