name: Mirror and run GitLab CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Mirror + trigger CI
        uses: SvanBoxel/gitlab-mirror-and-ci-action@master
        with:
          args: "https://gitlab.com/<namespace>/<repository>"
        env:
          GITLAB_HOSTNAME: "gitlab.peulen.xyz"
          GITLAB_USERNAME: "tpeulen"
          GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }} # Generate here: https://gitlab.com/profile/personal_access_tokens
          GITLAB_PROJECT_ID: "23" # https://gitlab.peulen.xyz/<namespace>/<repository>/edit
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret