#!/usr/bin/env python
# SPDX-License-Identifier: BSD-3-Clause
"""Build the published coverage matrix from the four runners' reports.

    python tools/conformance_matrix.py --report python=py.json --report r=r.json \
        --report java=java.json --report js=js.json --out doc/conformance.rst

Each runner writes its report to ``$TTTRLIB_CONFORMANCE_REPORT``; this merges
them into one table of case x language, so "R does not test the correlator" is a
row you can read rather than a fact you learn by opening four test suites.

A language with no report at all is reported as such rather than as a column of
failures -- not having run is different from having run and not passed, and the
table must not blur the two.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from typing import Dict, List, Tuple

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(REPO, "test", "conformance", "py"))

import cases as C  # noqa: E402

LANGUAGES = ("python", "r", "java", "js")
HEADINGS = {"python": "Python", "r": "R", "java": "Java", "js": "JavaScript"}

CELL = {"pass": "✓", "fail": "✗", "skip": "skip", "unsupported": "n/a"}


def load_reports(pairs: List[str]) -> Dict[str, Dict[str, dict]]:
    """language -> case id -> result."""
    out: Dict[str, Dict[str, dict]] = {}
    for pair in pairs:
        if "=" not in pair:
            raise SystemExit(f"--report wants language=path, got {pair!r}")
        lang, path = pair.split("=", 1)
        if lang not in LANGUAGES:
            raise SystemExit(f"unknown language {lang!r}; expected one of {LANGUAGES}")
        if not os.path.exists(path):
            print(f"no report for {lang} at {path}; the column will say 'not run'",
                  file=sys.stderr)
            continue
        with open(path, encoding="utf-8") as fh:
            doc = json.load(fh)
        out[lang] = {r["id"]: r for r in doc.get("results", [])}
    return out


def cell(result: dict | None) -> str:
    if result is None:
        return "—"          # the runner never reached this case
    return CELL.get(result["status"], result["status"])


def render(reports: Dict[str, Dict[str, dict]]) -> str:
    all_cases = C.load_all()
    by_area: Dict[str, List[dict]] = {}
    for area, case in all_cases:
        by_area.setdefault(area, []).append(case)

    lines: List[str] = []
    add = lines.append

    add(".. This file is generated by tools/conformance_matrix.py -- do not edit.")
    add("")
    add("Cross-language conformance")
    add("==========================")
    add("")
    add("Every case in ``test/conformance/cases/`` run by every binding. One case")
    add("list, four runners: the numbers below are *shared*, not four copies that")
    add("happen to agree. See ``test/conformance/README.md``.")
    add("")
    add("Legend: ✓ passed, ✗ failed, ``skip`` data unavailable, ``n/a``")
    add("declared unsupported for that binding, — that runner did not report.")
    add("")

    missing = [l for l in LANGUAGES if l not in reports]
    if missing:
        add(".. warning::")
        add("")
        add("   No report for: " + ", ".join(HEADINGS[l] for l in missing)
            + ". Those columns are blank because the runner did not execute,")
        add("   which is not the same as having nothing to run.")
        add("")

    totals = {l: {"pass": 0, "fail": 0, "skip": 0, "unsupported": 0} for l in LANGUAGES}

    for area in sorted(by_area):
        add(area)
        add("-" * len(area))
        add("")
        rows: List[Tuple[str, ...]] = []
        for case in by_area[area]:
            row = [case["id"]]
            for lang in LANGUAGES:
                r = reports.get(lang, {}).get(case["id"])
                if r is not None and r["status"] in totals[lang]:
                    totals[lang][r["status"]] += 1
                row.append(cell(r))
            rows.append(tuple(row))
        add(table(("case",) + tuple(HEADINGS[l] for l in LANGUAGES), rows))
        add("")

    add("Totals")
    add("------")
    add("")
    add(table(("", "passed", "failed", "skipped", "unsupported"),
              [(HEADINGS[l], str(totals[l]["pass"]), str(totals[l]["fail"]),
                str(totals[l]["skip"]), str(totals[l]["unsupported"]))
               for l in LANGUAGES]))
    add("")

    declared = [(c["id"], lang, why)
                for _, c in all_cases
                for lang, why in sorted(c.get("unsupported", {}).items())]
    if declared:
        add("Declared gaps")
        add("-------------")
        add("")
        add("A binding that cannot express a case says so in the case file, with a")
        add("reason. These are the gaps the suite knows about; anything else that")
        add("does not run is a bug.")
        add("")
        for case_id, lang, why in declared:
            add(f"``{case_id}`` — **{HEADINGS[lang]}**: {why}")
            add("")

    return "\n".join(lines) + "\n"


def table(header: Tuple[str, ...], rows: List[Tuple[str, ...]]) -> str:
    """A reStructuredText simple table, padded to the widest cell per column."""
    widths = [len(h) for h in header]
    for row in rows:
        for i, v in enumerate(row):
            widths[i] = max(widths[i], len(v))
    rule = "  ".join("=" * w for w in widths)
    out = [rule, "  ".join(h.ljust(w) for h, w in zip(header, widths)).rstrip(), rule]
    for row in rows:
        out.append("  ".join(v.ljust(w) for v, w in zip(row, widths)).rstrip())
    out.append(rule)
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--report", action="append", default=[],
                    metavar="LANG=PATH", help="a runner's JSON report")
    ap.add_argument("--out", default=os.path.join(REPO, "doc", "conformance.rst"))
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the file on disk differs from what would be written")
    args = ap.parse_args()

    text = render(load_reports(args.report))

    if args.check:
        current = ""
        if os.path.exists(args.out):
            with open(args.out, encoding="utf-8") as fh:
                current = fh.read()
        if current != text:
            print(f"{args.out} is out of date; regenerate it with "
                  f"tools/conformance_matrix.py", file=sys.stderr)
            return 1
        print(f"{args.out} is up to date")
        return 0

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write(text)
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
