function(tttrlib_find_python)
    FIND_PACKAGE(Python3 COMPONENTS Interpreter Development NumPy)
    INCLUDE_DIRECTORIES(BEFORE ${Python3_NumPy_INCLUDE_DIRS} ${Python3_INCLUDE_DIRS})
    LINK_LIBRARIES(${Python3_LIBRARIES})
    MESSAGE(STATUS "Python3_NumPy_INCLUDE_DIRS='${Python3_NumPy_INCLUDE_DIRS}'")
    MESSAGE(STATUS "Python3_INCLUDE_DIRS='${Python3_INCLUDE_DIRS}'")
    MESSAGE(STATUS "Python3_LIBRARIES='${Python3_LIBRARIES}'")
endfunction(tttrlib_find_python)