name: Conda Build

on:
  push:
    branches:
      - development  # You can change this to the branch you want to trigger on
  schedule:
    # Every Monday at 17PM UTC (9AM EST)
    - cron: "0 17 * * 1"

jobs:
  build-linux:
    name: CondaBuild (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.8", "3.11"]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true

      - name: Display Conda Settings
        shell: bash -el {0}
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
          printenv | sort

      - name: "Set SDK on MacOS (if needed)"
        if: startsWith(matrix.os, 'macos')
        run: tools/install_macos_sdk.sh

      - name: Build Conda Package
        shell: bash -el {0}
        run: |
          mamba install conda-build boa
          cd conda-recipe
          curl -sLO  https://raw.githubusercontent.com/conda-forge/conda-forge-pinning-feedstock/084b098a28a7a66e9a0967d156bc55b9ebfc6726/recipe/conda_build_config.yaml
          # curl -sLO https://github.com/conda-forge/conda-forge-pinning-feedstock/raw/main/recipe/conda_build_config.yaml
          conda mambabuild .
